version: "1.0"
info:
  model: int-scaffold
packages:
- name: Sgh0506Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
- name: SubstractPublicSvcPackage
  gitServerName: srcCtrl_AzRepos_Arti
  gitUrl: https://dev.azure.com/ArtiKhare/SubstractPublicSvcPackage/_git
  gitUsername: ArtiKhare
  gitBranch: main
- name: OpenWeatherClient
  wpmServer: https://packages.webmethods.io
  wpmRegistry: public
  wpmVersion: latest
